### ISSUE TITLE
Tips to improve your project even more

### ISSUE THREAD

**Issue by MahdiRezaeiDev** [Kelvin-Ben/To-Do-list#3]
Hello dear,
we have carefully reviewed your solution and found it excellent, and well-organized.
To highlight: 🎯

- Good usage of HTML semantic elements.
- No Linters error.
- Good git flow control.

Also here are some tips that will help you to improve your code even more. ❤️
- Nowadays code readability is an important topic as we all work in groups, so we kindly recommend using an empty line of space after every block of code.
- to store data in local storage we have to use the `localStorage.setItem()` method, so kindly consider using this method to store data in the local storage in order to use them later.
-

**Comment by Kelvin-Ben** [comment]
Thank you for the alert, I will apply the changes that you have suggested
